[book]
authors = ["blackanger"]
language = "en"
multilingual = false
src = "Samples"
title = "The Tao of Rust Programming"


[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]
mathjax-support = true

[output.html.playground]
editable = true
copy-js = true

[output.html.fold]
enable = true
level = 0